apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: microservices
  labels:
    app: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
      - name: loyalty-service
        image: loyalty-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef: 
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_DB
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: privateKey
        - name: PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: publicKey
        - name: GATEWAY_SERVICE_UUID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GATEWAY_SERVICE_UUID
        - name: BOOKING_SERVICE_UUID
          valueFrom:
            configMapKeyRef: 
              name: app-config
              key: BOOKING_SERVICE_UUID
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
  namespace: microservices
  labels:
    app: loyalty-service
spec:
  selector:
    app: loyalty-service
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP