apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: microservices
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: booking-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef: 
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_DB
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: privateKey
        - name: PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: publicKey
        - name: GATEWAY_SERVICE_UUID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GATEWAY_SERVICE_UUID
        - name: BOOKING_SERVICE_UUID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BOOKING_SERVICE_UUID
        - name: RABBITMQ_MQ_USER
          valueFrom:
            secretKeyRef: 
              name: app-secrets
              key: RABBIT_MQ_USER
        - name: RABBITMQ_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBIT_MQ_PASSWORD
        - name: RABBIT_MQ_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_HOST
        - name: RABBIT_MQ_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_PORT
        - name: RABBIT_MQ_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_QUEUE_NAME
        - name: RABBIT_MQ_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_MQ_EXCHANGE
        - name: HOTEL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_HOST
        - name: HOTEL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HOTEL_SERVICE_PORT
        - name: PAYMENT_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_HOST
        - name: PAYMENT_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_SERVICE_PORT
        - name: LOYALTY_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_HOST
        - name: LOYALTY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOYALTY_SERVICE_PORT              
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: microservices
  labels:
    app: booking-service
spec:
  selector:
    app: booking-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP