apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: microservices
data:

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

  BOOKING_DB: "reservations_db"
  SESSION_DB: "users_db"
  HOTEL_DB: "hotels_db"
  PAYMENT_DB: "payments_db"
  LOYALTY_DB: "balances_db"
  REPORT_DB: "statistics_db"

  RABBIT_MQ_HOST: "rabbitmq"
  RABBIT_MQ_PORT: "5672"
  RABBIT_MQ_QUEUE_NAME: "booking_queue"
  RABBIT_MQ_EXCHANGE: "booking_exchange"


  HOTEL_SERVICE_HOST: "hotel-service"
  HOTEL_SERVICE_PORT: "8082"
  PAYMENT_SERVICE_HOST: "payment-service"
  PAYMENT_SERVICE_PORT: "8084"
  LOYALTY_SERVICE_HOST: "loyalty-service"
  LOYALTY_SERVICE_PORT: "8085"
  SESSION_SERVICE_HOST: "session-service"
  SESSION_SERVICE_PORT: "8081"
  REPORT_SERVICE_HOST: "report-service"
  REPORT_SERVICE_PORT: "8086"
  BOOKING_SERVICE_HOST: "booking-service"
  BOOKING_SERVICE_PORT: "8083"

  GATEWAY_SERVICE_PORT: "8087"
  GATEWAY_SERVICE_UUID: "b51ceda2-bfa5-11eb-8529-0242ac130003"

  BOOKING_SERVICE_UUID: "911ccb4c-c055-11eb-8529-0242ac130003"
  
  publicKey: |- 
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvUNYZeqLLAoOU6+NyFtK\
    cdls9LQzikR53K3mXHsNxvut0Ll6y0m+QUYduKtHo+Fvlo/P+kUer8BtYRbTyAas\
    ujmFLxHQZjmsvXhKc0HNl8tud6kkMsXKOBZsjSwMH8pNCUuQynWoE+nLdwKkHvfq\
    BrBB39fAlg/3Z2K3yiOuOLqp4iNy865PmJyMGfAQoSjDeNKne15EblrCQRhCa/oa\
    dRdSr2mGz8/4KrwSUviJRt+/+pjtcaDGg3z8RFAiWx4lkvD3EngvU5ZVVbQvqMj5\
    0M2BGwYe2X8W8AA98uRVt6sVjd97EOd12h+8x6J3TAECeoUETgm+jJf9GwSn1NIc\
    /QIDAQAB
