apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: microservices
  labels:
    app: session-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: session-service:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef: 
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_DB
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: privateKey
        - name: PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: publicKey
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: microservices
  labels:
    app: session-service
spec:
  selector:
    app: session-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP